var btn = document.getElementById("add_new");
var btn2 = document.getElementById("add_new2");
var addNewGame = document.getElementById("addNewGame")
var addNewGame2 = document.getElementById("addNewGame2")
function addGame(formInputId){
  var opponentName = document.createElement("input")
  opponentName.setAttribute("type", "text")
  opponentName.setAttribute("name", "opponent")
  opponentName.setAttribute("placeholder", "opponent name")
  var userScore = document.createElement("input")
  userScore.setAttribute("type", "number")
  userScore.setAttribute("name", "userScore")
  userScore.setAttribute("placeholder", "your score")
  var opponentScore =  document.createElement("input")
  opponentScore.setAttribute("type", "number")
  opponentScore.setAttribute("name", "opponentScore")
  opponentScore.setAttribute("placeholder", "their score")
  var submit = document.createElement("input")
  submit.setAttribute("type", "submit")
  formInputId.appendChild(opponentName)
  formInputId.appendChild(userScore)
  formInputId.appendChild(opponentScore)
  formInputId.appendChild(submit)
}

btn.addEventListener("click", function(){
  var opponentName = document.createElement("input")
  opponentName.setAttribute("type", "text")
  opponentName.setAttribute("name", "opponent")
  opponentName.setAttribute("placeholder", "opponent name")
  var userScore = document.createElement("input")
  userScore.setAttribute("type", "number")
  userScore.setAttribute("name", "userScore")
  userScore.setAttribute("placeholder", "your score")
  var opponentScore = document.createElement("input")
  opponentScore.setAttribute("type", "number")
  opponentScore.setAttribute("name", "opponentScore")
  opponentScore.setAttribute("placeholder", "their score")
  var submit = document.createElement("input")
  submit.setAttribute("type", "submit")
  addNewGame.appendChild(opponentName)
  addNewGame.appendChild(userScore)
  addNewGame.appendChild(opponentScore)
  addNewGame.appendChild(submit)
 })
btn2.addEventListener("click", function(){
  var opponentName = document.createElement("input")
  opponentName.setAttribute("type", "text")
  opponentName.setAttribute("name", "opponent")
  opponentName.setAttribute("placeholder", "opponent name")
  var userScore = document.createElement("input")
  userScore.setAttribute("type", "number")
  userScore.setAttribute("name", "userScore")
  userScore.setAttribute("placeholder", "your score")
  var opponentScore = document.createElement("input")
  opponentScore.setAttribute("type", "number")
  opponentScore.setAttribute("name", "opponentScore")
  opponentScore.setAttribute("placeholder", "their score")
  var submit = document.createElement("input")
  submit.setAttribute("type", "submit")
  addNewGame2.appendChild(opponentName)
  addNewGame2.appendChild(userScore)
  addNewGame2.appendChild(opponentScore)
  addNewGame2.appendChild(submit)
 })
